# Generated by Django 3.2.8 on 2022-10-01 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JovianApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='galery',
            name='image',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
