# Generated by Django 3.2.8 on 2022-10-02 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JovianApp', '0002_alter_galery_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('image', models.ImageField(null=True, upload_to='images/gallery/')),
            ],
        ),
        migrations.DeleteModel(
            name='Galery',
        ),
        migrations.AddField(
            model_name='images',
            name='mapProjected',
            field=models.ImageField(null=True, upload_to='images/blue_img/', verbose_name='Map Projected'),
        ),
        migrations.AlterField(
            model_name='images',
            name='blueImage',
            field=models.ImageField(null=True, upload_to='images/blue_img/', verbose_name='Blue Image'),
        ),
        migrations.AlterField(
            model_name='images',
            name='greenImage',
            field=models.ImageField(null=True, upload_to='images/green_img/', verbose_name='Green Image'),
        ),
        migrations.AlterField(
            model_name='images',
            name='redImage',
            field=models.ImageField(null=True, upload_to='images/red_img/', verbose_name='Red Image'),
        ),
    ]
